<!DOCTYPE html>


<div class="text-center">
    
    <h1 class="text-3xl font-bold mb-4">Update ID</h1>
    
    <form action= "" method="POST" class="space-y-4">
        <div class="mb-4">
            <input type="text" name="id" class="border border-gray-300 p-2 rounded w-full" placeholder="id" />
        </div>
        <div>
            <button type="submit" class="flex items-center justify-center w-full px-4 py-2 bg-indigo-600 text-white font-medium text-sm rounded-lg hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition duration-150 ease-in-out">
            <a href = "<?php echo WEB_ROOT?>/update/ <?php echo $task['id'];?>">
            <svg class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11H9v4h4v-2H10v-2z" clip-rule="evenodd" />
                </svg>
                Search Task
            </button>
        </div>