    <div class="text-center">
        <h1 class="text-3xl font-bold mb-4">Read To-Do</h1>

    <?php if ($this->tasks): ?>
        <!-- <p>Dades ok</p> -->
        <div class="mt-4 p-4 bg-gray-100 rounded">
            <!-- <h2 class="text-xl font-semibold">To-Do List</h2><br> -->
            <div class="flex flex-wrap justify-center space-x-4">
            <?php foreach ($this->tasks as $index => $task): ?>
                <!-- <p>Estic dins del foreach</p> -->
                <div class="flex flex-col items-center w-1/4 p-2">
                    <div class="border border-gray-300 rounded-lg p-4 w-full">
                        <form class="space-y-4">

                            <div class="mb-4">
                                <span type="text" name="user"><?= htmlspecialchars($task['user']) ?></span>
                            </div>

                            <div class="mb-4">
                                <span type="text" name="title"><?= htmlspecialchars($task['title']) ?></span>
                            </div>

                            <div class="mb-4">
                                <span type="text" name="status"><?= htmlspecialchars($task['status']) ?></span>
                            </div>

                            <div class="mb-4">
                                <label for="start-date" class="block text-sm font-medium text-gray-700">Start Date</label>
                                <span type="text" id="start-date" name="start-date"><?= htmlspecialchars($task['start_date']) ?></span>
                            </div>

                            <div class="mb-4">
                                <label for="end-date" class="block text-sm font-medium text-gray-700">End Date</label>
                                <span type="text" id="end-date" name="end-date"><?= htmlspecialchars($task['end_date']) ?></span>
                            </div>

                        </form>
                    <hr class="my-4">
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    <?php else: ?>
        <p class="text-red-500 mt-4">No tasks found.</p>
    <?php endif; ?>
        
        <a href="<?php echo WEB_ROOT ?>" class="inline-block mt-6">
            <button class="flex items-center justify-center w-12 h-12 bg-blue-600 text-white rounded-full hover:bg-blue-700 transition-all duration-300 ease-in-out">
                <svg class="w-6 h-6 transform transition-transform hover:rotate-360 duration-500" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M11 17l-5-5m0 0l5-5m-5 5h12"></path>
                </svg>
            </button>
        </a>
    </div>