<body class="flex items-center justify-center h-screen bg-gray-100">

    <div class="text-center">
        <h1 class="text-3xl font-semibold text-center text-green-500 dark:text-green-400">TASK ADDED SUCCESSFULLY!</h1>
        <p class="text-lg text-gray-600">You will be redirected to the homepage in <span id="countdown">3</span> seconds...</p>
    </div>

    <script>
    let countdownElement = document.getElementById('countdown');
    let countdownValue = 3;

    const countdownTimer = setInterval(() => {
        countdownValue--;
        countdownElement.textContent = countdownValue;

        if (countdownValue <= 0) {
            clearInterval(countdownTimer);
            window.location.href = "/Sprint3/DEVELOPERS/XaSe/web";
        }
    }, 1000);
</script>
</body>